from pretty_html_table import build_table
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys

msg = MIMEMultipart()
msg['Subject'] = 'Daily Status'
msg['From'] = "utsavprajapati30003000@gmail.com"
msg["To"] = "utsavprajapati3000@gmail.com" 

html = """\
<html>
<head>
</head>

<body>
<p>
Hi All,<br>
<br>Please find below the daily status<b>{0}</b>: - <br>

<br><font size="-1">Note: This is an autogenerated email. Please do not reply.</font>
</p>
</body>

</html>
""".format('pass')

part1 = MIMEText(html, 'html')
msg.attach(part1)

server = smtplib.SMTP('smtp.1and1.com', 587)
server.starttls()
server.login('utsavprajapati30003000@gmail.com', 'Utsav@88728')

server.sendmail(msg['From'], ["utsavprajapati30003000@gmail.com"], msg.as_string())